### ISSUE TITLE
How to change TextMesh Pro's Text by clicking a button? (script)

### ISSUE THREAD

**Issue by steviegt6** [Steviegt6/WatchPaintDry#1]
Hi, all, I was wondering: How can I change (preferable randomize from a string) the text of a button. (The text from TextMesh Pro, which looks way better; If you can provide me with a better alternative to TextMesh Pro that's easier to use and is more popular, tell me, as well.)

**Comment by steviegt6** [comment]
https://www.youtube.com/watch?v=WCgd_HY1F14
^^^ Possible solution. (Can't work on it right now)

**Comment by valkyrienyanko** [comment]
Get its text component and change its text value.

```cs
TextMeshPro textmeshPro = GetComponent<TextMeshPro>();
textmeshPro.SetText("MyText");
```

Source: http://digitalnativestudios.com/textmeshpro/docs/ScriptReference/TextMeshPro-SetText.html

**Comment by steviegt6** [comment]
I have decided on doing this diferently, so I am closing this issue. I may re-open it later on.
