### ISSUE TITLE
Add music. (Recommendations)

### ISSUE THREAD

**Issue by steviegt6** [Steviegt6/WatchPaintDry#3]
Title.

**Comment by steviegt6** [comment]
https://www.fesliyanstudios.com/royalty-free-music/download/deep-meditation/310
^^ Possible title screen music.

**Comment by steviegt6** [comment]
https://www.youtube.com/watch?v=QAH1-zgc5mE
^^ Potential guide. (Can't try right now.)

**Comment by valkyrienyanko** [comment]
https://www.youtube.com/watch?v=C-CG5w4YwOI

**Comment by steviegt6** [comment]
Music has been added.
